### ISSUE TITLE
RAG has any conversion limitation? 

### ISSUE THREAD

**Issue by Gurushesh-Metapercept** [pymupdf/RAG#100]
Can we use this tool an unlimited number of times for pdt2md conversion, or does it have a daily limit, such as 1000 pages per day, or something else?

**Comment by JorjMcKie** [comment]
Please review the license, GNU AGPL 3.0 to confirm that it does apply to you. To make sure you should also contact https://artifex.com/contact/.

**Comment by JorjMcKie** [comment]
Other than license considerations, there are no restrictions for using the software.
