### ISSUE TITLE
pymypdf4llm的一些问题，大家有没有遇到

### ISSUE THREAD

**Issue by orcharddd1990** [pymupdf/RAG#106]
问题
1）基本格式不对啊，行间距，括号中的数字，省略号
2）英文文档无法识别
优点
字体基本可以识别，图片可以提取

<img width="521" alt="pymupdf4llm_原pdf段落_2024-08-21_10-30-56" src="https://github.com/user-attachments/assets/80052717-8e0f-4b66-8172-33f72ff7e390">
<img width="451" alt="test001pdf转md_格式不对_不对_2024-08-21_10-32-07" src="https://github.com/user-attachments/assets/b6ad839b-8241-48f3-97ee-4412271a6239">

**Comment by JorjMcKie** [comment]
We only accept **_English_** as the language to post in Issues or Discussions, sorry.
This is to control effort for our maintenance team and to keep the best possible benefit for other users.
