### ISSUE TITLE
While trying to use pymupdfllm to save an image, I get the following error: Invalid bandwriter header dimensions/setup

### ISSUE THREAD

**Issue by neilbhutada** [pymupdf/RAG#112]
When trying to convert this [pdf](https://www.nice.org.uk/guidance/mib53/resources/aquilion-prime-ct-scanner-for-imaging-coronary-artery-disease-in-adults-in-whom-imaging-is-difficult-pdf-63499224847813) into a markdown file, and state write_images = True:
- I get the following error. pymupdf.mupdf.FzErrorArgument: code=4: Invalid bandwriter header dimensions/setup

**Comment by JorjMcKie** [comment]
Cannot access the PDF using above link.

**Comment by neilbhutada** [comment]
Here is the pdf: 
[aquilion-prime-ct-scanner-for-imaging-coronary-artery-disease-in-adults-in-whom-imaging-is-difficult-pdf-63499224847813.pdf](https://github.com/user-attachments/files/16750026/aquilion-prime-ct-scanner-for-imaging-coronary-artery-disease-in-adults-in-whom-imaging-is-difficult-pdf-63499224847813.pdf)

**Comment by JorjMcKie** [comment]
I found the problem: one of the images on page 0 has height width=0.
Ignoring such cases solves the problem.

**Comment by neilbhutada** [comment]
Is that something you will include in your package, or we would have to check for the by first parsing through the pdf. But I don't want to parse through the pdf another time to collect height and width dimensions. Should I try to see if I can edit the code base for height and width, and if you can give some direction on this?

**Comment by JorjMcKie** [comment]
@neilbhutada no, this will be fixed in the package of course.

**Comment by JorjMcKie** [comment]
Solved in v0.0.13.
