### ISSUE TITLE
Pymupdf4llm returns garbage values during parsing a simple page.

### ISSUE THREAD

**Issue by AhsanAli1116** [pymupdf/RAG#118]
I have a PDF of around 300 pages. When I extract it using pymupdf4llm. It returns bytes like encoded text and miss the information.

**Comment by JorjMcKie** [comment]
Nothing can be done if you do not include the example file!

**Comment by JorjMcKie** [comment]
One font embedded in your file does not contain a (valid) backtranslation table (CMAP) for the glyphs displayed. Therefore, no meaningful text can be extracted.
You also do not use the most current package version, otherwise you would have seen lots of &#xfffd; characters in your output.

**Comment by AhsanAli1116** [comment]
thanks

**Comment by AhsanAli1116** [comment]
> One font embedded in your file does not contain a (valid) backtranslation table (CMAP) for the glyphs displayed. Therefore, no meaningful text can be extracted. You also do not use the most current package version, otherwise you would have seen lots of � characters in your output.

is there any workaround for this?

**Comment by JorjMcKie** [comment]
No, there is not. You could of course OCR the file, but this would also mean losing other, valuable information like vector graphics. Many of the characters on page also are completely ok.
