### ISSUE TITLE
PyMUPDF4llm to_markdown() parallel execution

### ISSUE THREAD

**Issue by lequan310** [pymupdf/RAG#121]
```python
def load_resume(path: str):
    resume = pymupdf.open(path)
    resume_text = pymupdf4llm.to_markdown(resume, margins=(0))
    return resume_text
```

I'm trying to execute the code above in parallel to get multiple markdown for different files asynchronously using LangGraph.  I got the following error: 
ValueError: not a textpage of this page

Does anyone know what the problem is?

**Comment by JorjMcKie** [comment]
You must be using this in a Python threading environment.
This package is based on PyMuPDF. PyMuPDF does not support Python threading and will generate errors like the above. For more information please see the documentation [here](https://pymupdf.readthedocs.io/en/latest/recipes-multiprocessing.html#multiprocessing).
