### ISSUE TITLE
Error when executing the method 'pdf4llm.to_markdown()' in python.

### ISSUE THREAD

**Issue by Fianax** [pymupdf/RAG#125]
I am using pdf4llm to transform a pdf to markdown but when I use the method 'to_markdown' and pass the pdf path I get this error 'not a textpage of this page'.

This would be the code that I execute:
```
md_text = ''
    try:
        md_text = pdf4llm.to_markdown(path_pdf)
        if(md_text != ''):
            pathlib.Path(path_md).write_bytes(md_text.encode())
    except Exception as e:
        print(f'Error, to_markdown => ${path_pdf} Error => {e}')

    return md_text
```

This code is inside a method that is executed when I make a call to an api (with fast-api python) that I have running locally.

When I have executed it without api or anything it has not failed me but it has been to put it in an execution of an endpoint and when several users call to that endpoint it fails me in some of the pdf, not in all of them.

Any idea why this might be or what the error 'not a textpage of this page' means?

**Comment by JorjMcKie** [comment]
PyMuPDF4llM, like PyMuPDF cannot be used in an environment using Python threads see [here](https://pymupdf.readthedocs.io/en/latest/recipes-multiprocessing.html#multiprocessing).
