### ISSUE TITLE
Code logic duplicate

### ISSUE THREAD

**Issue by CedricLor** [pymupdf/RAG#129]
Less than an issue, it is a comment on the code in `pymupdf_rag.py` relating to the way the tables and image/vg are pushed to the md string.

Line 399 to line 448 in nested function `write_text` output the tables, images and graphics that are "above this text block", this text block being in this context one of the raw_lines inside a text rectangle.

Line 774 and 775 in `get_page_output` do the same thing but while iterating over the text rectangles.

I've tested commenting out the block from 399 to 448 and converting various PDF documents. From what I saw, it seems to me that the only difference in the resulting `md` strings is a couple less `\n`and whitespace.

There might be a special case I am missing and where line 399 to line 448 make sense, but it seems to me that since we already mapped the table, text, image, vg rectangles before `get_page_output` and `get_page_output` iterates at the rectangles level (and also handles table/img/vg rectangles below the text), the part of the code dealing with tables/images/vg rectangles inside the nested `write_text` (line 399 to line 448) should/could be safely removed without removing any feature.

Cédric

**Comment by CedricLor** [comment]
I made some additional test on another document with a complexed nesting of text, images and tables and it does indeed make a difference.

This thread should be closed.

**Comment by JorjMcKie** [comment]
Thanks for your observation!

This will be resolved in the regular ongoing further development.
