### ISSUE TITLE
Useless variable graphics = [] in pymupdf_rag.py

### ISSUE THREAD

**Issue by CedricLor** [pymupdf/RAG#130]
Hi,

In module `pymupdf_rag.py`, in nested function `get_page_output`, a list variable `graphics = []` is defined on line 703.

No other value is ever assigned to this variable, nothing is appended to the list, nor the list ever extended. It is however returned by `get_page_output` and unpacked to another `graphics` variable in the main function `to_markdown` on line 840 and then appended as a value to key `graphics` to the `document_output` list of dictionaries.

I am not so sure what was meant to be returned here. Based on the other components of the `document_output` dict, I understand that it should be a list. However, should it be the `actual_paths` list, the clusters' rectangle list `vg_clusters0` or something else?

Regards,

Cédric

**Comment by JorjMcKie** [comment]
This variable is placeholder for later use.
