### ISSUE TITLE
Problem with multiple columns in simple text

### ISSUE THREAD

**Issue by pascucg** [pymupdf/RAG#135]
Hello, I see that in some cases the columns are not processed correctly.
It jumps from information in one column to another, causing the resulting information to be out of order and incorrect.

I provide you with an example pdf where it occurs:
[ejemplo.pdf](https://github.com/user-attachments/files/16977923/ejemplo.pdf)

I also show you the problem below:
![column_error_example](https://github.com/user-attachments/assets/a509975e-5c2f-4823-8e61-cb6af403ddcd)

If I process the pdf with pymupdf, it does it correctly:
![column_correct_example](https://github.com/user-attachments/assets/ca55ce4a-3540-4907-816f-f21e6db4f91e)

**Comment by JorjMcKie** [comment]
I found the problem: The joining of original text blocks happens too aggressively, so the page number at the bottom gets joined and recursively causes all the text on page being joined in one big single block.
This causes nonsense to come out in the end.

As a quick fix, you can use `margins=(0, 0, 0, 72)` to ignore the page number block.

**Comment by JorjMcKie** [comment]
Fixed in version 0.0.15.

**Comment by pascucg** [comment]
Hello @JorjMcKie ,

Thank you for the fix, I have tested it in version 0.0.16 and it works correctly.

Running tests I see another problem that I indicate below.

In some documents the first line of the page is omitted.

I show you an example below.
[ejemplo.pdf](https://github.com/user-attachments/files/17024243/ejemplo.pdf)

![ejemplo](https://github.com/user-attachments/assets/f50cf72e-c245-4cbb-a04a-5de7ec1bd815)

**Comment by JorjMcKie** [comment]
No, this works for `margins=0`:
![image](https://github.com/user-attachments/assets/7d6a1674-2bf0-4990-aed5-ddcb91b1d767)

**Comment by pascucg** [comment]
You are right, using:
doc = pymupdf4llm.to_markdown('ejemplo.pdf', page_chunks=True, margins=0)

It works correctly.

Thank you
