### ISSUE TITLE
Table is not extracted and some text order was wrong for this PDF 

### ISSUE THREAD

**Issue by bbfrog** [pymupdf/RAG#138]
hi, I am testing converting this pdf to markdown text: 
https://www.jacionline.org/action/showPdf?pii=S0091-6749%2822%2901181-2

There are two problems: the second problem is more important. Thanks!
1. All tables in this PDF (Page 4, 6, 9) are not extracted as markdown format.
2. The text order in page 4 is wrong: The right panel text (starts with "relationship. The multiple..") is before the left panel text (starts with "with CSU was investigated..."). Page 7 has the same problem.

**Comment by JorjMcKie** [comment]
I cannot do anything about the tables: this type can simply not be detected by the table finder.
But the other aspect - the one more important for you - has a fix, which will be part of the next version.

**Comment by bbfrog** [comment]
> I cannot do anything about the tables: this type can simply not be detected by the table finder. But the other aspect - the one more important for you - has a fix, which will be part of the next version.

Great, thank JoriMcKie very much! Could you please let me know the release date of the next version?

**Comment by JorjMcKie** [comment]
Fixed in version 0.0.15.

**Comment by bbfrog** [comment]
Thanks very much!
