### ISSUE TITLE
version v.015 missing pix.save(image_filename)

### ISSUE THREAD

**Issue by kingennio** [pymupdf/RAG#140]
I've just installed the latest v.015 and I noticed images are no longer saved in the folder even with write_images=True
 I noticed that in the text md the correct links to the imeages are written. Then I stepped through with the code and I think I found the issue: in function save_image, line 365 returns image_filename w/o first saving the image with pix.save(image_filename).
I've added the missing line of code and now it works fine.

**Comment by JorjMcKie** [comment]
Oops - thanks for the report.
Will fix this soon.

**Comment by JorjMcKie** [comment]
Fixed with version 0.0.16
