### ISSUE TITLE
Normal body text parsed as headers

### ISSUE THREAD

**Issue by tanchangsheng** [pymupdf/RAG#143]
Normal body text words has been parsed as headers.

file: [example.pdf](https://github.com/user-attachments/files/17029517/example.pdf)
```
# IT Inventory System Tender Specifications

### Organization: XYZ Solutions Inc. Date: April 23, 2024
```
<img width="854" alt="image" src="https://github.com/user-attachments/assets/736d3897-dd33-4121-a627-a1f2da34e299">

**Comment by JorjMcKie** [comment]
This is not a bug:
The header identification algorithm determines the most frequent font size and sets it as the body text. Everything smaller will also be treated as body text.
The maximum 6 font sizes will be treated as headers h1 - h6. Any font size larger than body text but smaller than font size of h6 will be treated like h6.
We all know that this algorithm is an approximation of any document's truth.
Use your own logic if you cannot agree with this approach.

**Comment by tanchangsheng** [comment]
Thanks for the clarification!
