### ISSUE TITLE
Multiple lines parsed as single line

### ISSUE THREAD

**Issue by tanchangsheng** [pymupdf/RAG#144]
Words across two lines parsed as single line.

file: [example.pdf](https://github.com/user-attachments/files/17029517/example.pdf)

Expected output:
```
**Organization:** XYZ Solutions Inc.  
**Date:** April 23, 2024
```

Actual Output
```
### Organization: XYZ Solutions Inc. Date: April 23, 2024
```
<img width="854" alt="image" src="https://github.com/user-attachments/assets/736d3897-dd33-4121-a627-a1f2da34e299">

**Comment by JorjMcKie** [comment]
Not a bug. There is no indication whatsoever from which to conclude a paragraph break.
So the logic behaves correctly in assuming continuous text.

**Comment by JorjMcKie** [comment]
Also that font size obviously fell in the range of header font sizes.
If you do not like that logic, either switch it off (`hdr_info=False`) altogether or supply your own.
In any case: the 2 lines follow each other with no extraneous spacing, therefore no extra line break is being generated.

**Comment by tanchangsheng** [comment]
Thanks for the clarification!
