### ISSUE TITLE
No module named 'get_text_lines' in pymupdf4llm

### ISSUE THREAD

**Issue by vzegna** [pymupdf/RAG#15]
### Description of the bug

I am trying to convert a PDF to markdown and I keep getting this error:

```
    import pymupdf4llm
  File "/home/vzegna/pyvenv/lib/python3.11/site-packages/pymupdf4llm/__init__.py", line 1, in <module>
    from .helpers.pymupdf_rag import to_markdown, IdentifyHeaders
  File "/home/vzegna/pyvenv/lib/python3.11/site-packages/pymupdf4llm/helpers/pymupdf_rag.py", line 46, in <module>
    from get_text_lines import get_raw_lines, is_white
ModuleNotFoundError: No module named 'get_text_lines'
```

This was working until few days ago, but it stopped after I upgraded packages today.
The current pymupdf4llm version I have installed is 0.0.2.
I have downgraded to 0.0.1, and the issue does not appear anymore.
I assume someone might have inadvertently removed 'get_text_lines' from the code.

### How to reproduce the bug

This is what I am doing in my Python code (I extracted the only relevant lines just for reference):

```
import pymupdf4llm
import pymupdf

pdf_doc = pymupdf.open("/my_pdf_file_path.pdf")
md_text = pymupdf4llm.to_markdown(pdf_doc)
```

The error is thrown when the code gets to the to_markdown() method.

### PyMuPDF version

1.24.4

### Operating system

Linux

### Python version

3.11

**Comment by JorjMcKie** [comment]
This has been resolved in v0.0.3.
