### ISSUE TITLE
pymupdf4llm markdown function missing first and last line on every page

### ISSUE THREAD

**Issue by Devvarat** [pymupdf/RAG#151]
`pymupdf4llm.to_markdown(filepath)`
to_markdown() function is missing first and last line on page. Underline pymupdf get_text() function works fine and return the complete page text.

**Comment by JorjMcKie** [comment]
What did you use as `margins` parameter?

**Comment by Devvarat** [comment]
Did not use any margins. Can you recommend any specific margin value that might work?

**Comment by Devvarat** [comment]
Hi JorjMcKie, Thanks for the reply. Playing with `margins` parameter solved our issue.

**Comment by JorjMcKie** [comment]
Please consult the documentation: the default margins value is `(0, 50, 0, 50)`, so stripes of height 50 are ignored at top and bottom of each page. Use `margins=0` in your case.
