### ISSUE TITLE
Some pdf pages takes lot of time to converting.

### ISSUE THREAD

**Issue by imran-pyflow** [pymupdf/RAG#157]
[FinalCLStudy.md](https://github.com/user-attachments/files/17177481/FinalCLStudy.md)
Page no 59 is taking more than 300seconds to finish.

Check below code.
File: **pymupdf_rag.py**
function: get_page_output.
```python
            for i in range(len(img_info) - 1, 0, -1):
                r = img_info[i]["bbox"]
                if r.is_empty:
                    img_info.pop(i)
                    continue
                for j in range(i):  # image areas larger than r
                    if r in img_info[j]["bbox"]:
                        #del img_info[i]  # contained in some larger image
                        img_info.pop(i)
                        break

```

**Comment by imran-pyflow** [comment]
It is calculating image information even If the write_iamges = False

**Comment by JorjMcKie** [comment]
If you want to report a bug, always provide a reproducing file.
Else, image information is needed in any case to compute text candidate areas.
Duration is mainly dependent on the number of vector graphics on page.

**Comment by imran-pyflow** [comment]
[Sample file](https://drive.google.com/file/d/1nLHFNpe3uysf9Qrug4hE7oDQY2gkTAxY/view)
