### ISSUE TITLE
Titles that do not convert to markdown titles

### ISSUE THREAD

**Issue by Fianax** [pymupdf/RAG#165]
Hello again

I have a pdf (created from a word) that when I transform it to markdown, some indices are not marked with the corresponding '#####'.

What is the reason?

Because I have looked at the word and the content always has the same font size and the indices more, although only one unit larger.

I attach both the pdf, word and the markdown created.

[prueba_indices_no_detectados.docx](https://github.com/user-attachments/files/17280770/prueba_indices_no_detectados.docx)
[prueba_indices_no_detectados.md](https://github.com/user-attachments/files/17280774/prueba_indices_no_detectados.md)
[prueba_indices_no_detectados.pdf](https://github.com/user-attachments/files/17280776/prueba_indices_no_detectados.pdf)

with pdf4llm version==0.0.9

Thanks

**Comment by JorjMcKie** [comment]
Detecting headlines is based on a fairly simple algorithm - as documented:
A full document scan is performed and all occurring font sizes are classified by their "popularity". The most popular one becomes "body text". Larger ones are assigned to up to the 6 HTML header levels.
That's all.
Colors like in your example, or bold, italics or other properties are ignored.
