### ISSUE TITLE
Ligatures are not properly handled converting to MD

### ISSUE THREAD

**Issue by DiazBejaranoD** [pymupdf/RAG#175]
When uploading documents with fonts that contain double letter ligatures, they are not correctly parsed into Markdown.
Example Font: Aptos Display

Original PDF:
![image](https://github.com/user-attachments/assets/01255027-d6af-49ff-879b-31c5550a35d6)

Converted MD:
![image](https://github.com/user-attachments/assets/6920203a-ee6c-4789-92f7-4495a27d4958)

**Comment by DiazBejaranoD** [comment]
you are right, this is also happening on PyMuPDF. I'll open the issue then.
[FAQ_travels_in_EU.pdf](https://github.com/user-attachments/files/17509553/FAQ_travels_in_EU.pdf)

**Comment by JorjMcKie** [comment]
You can stop doing this:
This is an error (damaged / incomplete font) in the PDF itself. All text extraction tools extract `o7er` instead of `offer`.
