### ISSUE TITLE
Feature request: inlined base64 images in markdown format

### ISSUE THREAD

**Issue by sglebs** [pymupdf/RAG#176]
I would like to suggest that the image extraction could also be done in inlined markdown format (controlled by a flag) using base64 instead of an external file.  Here's the code:

```
b64_format = base64.b64encode(png_data)
markdown_format = f"![](data:image/png;base64,{b64_format.decode('utf-8')})"
```
If you can add the title & alt, even better. Not sure if you have these values in the PDF.

Thanks for listening, thanks for the lib, great job!

**Comment by JorjMcKie** [comment]
This already supported via the `embed_images` parameter.
Caption, title etc. are not systematically detectable at all and will therefore never be supported.
