### ISSUE TITLE
Extract Table Content Only for Each Page to Store as Metadata

### ISSUE THREAD

**Issue by QuangTQV** [pymupdf/RAG#179]
Description: Would it be possible to extract only the table content for each page individually? I am working on building a Retrieval-Augmented Generation (RAG) application, and I want to store metadata for each page containing only the table content. This would enable more accurate retrieval and better structuring of data specifically for pages with tables.
or just the image of the table is fine (not the image of the whole page, because LLM is very bad at extracting table content from the image of the whole page), then I will give it to LLM to extract the table information
Thank you for considering this feature!

**Comment by JorjMcKie** [comment]
Let me better understand your request:
You are interested in a feature that only returns table information from each page (and nothing if no table present).

If this is true, then native PyMuPDF would serve you much better / more directly than this derived package PyMuPDF4LLM.
Please consider this little snippet:
```python
import pymupdf
doc=pymupdf.open("input.pdf")
print(f"Scanning {doc.name=} for table information ...")
for page in doc:
    tabs = page.find_tables()
    if not tabs.tables:  # no tables there
        continue
    print(f"Page {page.number} contains {len(tabs.tables)} tables.")
    for i, tab in enumerate(tabs):  # walk through the tables
        md = tab.to_markdown()  # extract table content as markdown 
        pix = page.get_pixmap(clip=tab.bbox)  # table area as an image
        # more table meta info available like
        # tab.row_count, tab.col_count, etc.
```
What do you think?

**Comment by QuangTQV** [comment]
> Hãy để tôi hiểu rõ hơn về yêu cầu của bạn: Bạn quan tâm đến tính năng chỉ trả về thông tin bảng từ mỗi trang (và không trả về thông tin gì nếu không có bảng nào).
> 
> Nếu điều này là đúng, thì PyMuPDF gốc sẽ phục vụ bạn tốt hơn nhiều/trực tiếp hơn so với gói PyMuPDF4LLM phái sinh này. Vui lòng xem xét đoạn trích nhỏ này:
> 
> ```python
> import pymupdf
> doc=pymupdf.open("input.pdf")
> print(f"Scanning {doc.name=} for table information ...")
> for page in doc:
>     tabs = page.find_tables()
>     if not tabs.tables:  # no tables there
>         continue
>     print(f"Page {page.number} contains {len(tabs.tables)} tables.")
>     for i, tab in enumerate(tabs):  # walk through the tables
>         md = tab.to_markdown()  # extract table content as markdown 
>         pix = page.get_pixmap(clip=tab.bbox)  # table area as an image
>         # more table meta info available like
>         # tab.row_count, tab.col_count, etc.
> ```
> 
> Bạn nghĩ sao?

Thank you for your enthusiasm. However, after testing the code you provided, the extracted tables have several areas that aren’t accurate.

**Comment by JorjMcKie** [comment]
This is a different argument though. If PyMuPDF does not correctly detect a table, then PyMuPDF4LLM cannot either.
**_If_** tables pose no detection problem for our algorithm, then my "enthusiastic" snippet should deliver what you want.
