### ISSUE TITLE
pymupdf4llm' has no attribute 'to_markdown

### ISSUE THREAD

**Issue by andrey4763913** [pymupdf/RAG#186]
I have
pip list | grep -i pdf
PyMuPDF 1.24.13
pymupdf4llm 0.0.17
(TEST) [shevel@homedesk TEST]$ python -V
Python 3.12.1

and still have "AttributeError: partially initialized module 'pymupdf4llm' has no attribute 'to_markdown' (most likely due to a circular import)"
Any ideas ?

**Comment by andrey4763913** [comment]
Hi eveybody,

strange error above was by only cause that my test file had the name pumupdf4llm.py !
After changing the test file name to myt.py all things go work as expected!

Good luck for all of us!

**Comment by jamie-lemon** [comment]
@andrey4763913 You had this issue: https://stackoverflow.com/questions/59762996/how-to-fix-attributeerror-partially-initialized-module :)
