### ISSUE TITLE
Text missing that was detected by pymupdf standard

### ISSUE THREAD

**Issue by sebkouba** [pymupdf/RAG#190]
I was trying to extract information from amazon bills and the bill identifier wasn't anywhere to be found in the 4llm package markdown. I went back to oldschool pymupdf which extracted the text without issues.

This is a customer file so I can't upload it but maybe this saves somebody else some time.

**Comment by JorjMcKie** [comment]
I don't think this will help anyone as it is.
And without a reproducing file, we anyway cannot accept this post as a bug report.
You probably didn't notice that there is a default margin that ignores stuff near the top and the bottom of pages.

**Comment by MarcDAFrame** [comment]
I can replicate this issue

Here's the code I'm using to run
```
import fitz
import pymupdf4llm
raw = open('./4.pdf', 'rb').read()
pdf_file = fitz.open(stream=raw, filetype="pdf")
md_text = pymupdf4llm.to_markdown(pdf_file)
print(md_text)
```

Here's my versions
```
Python 3.9.6
fitz='1.24.13'
pymupdf4llm='0.0.17'
```

And attached is the file that I'm using
[4.pdf](https://github.com/user-attachments/files/18072818/4.pdf)

**Comment by MarcDAFrame** [comment]
found the solution downgrade from 0.0.17 to 0.0.16

https://github.com/pymupdf/RAG/issues/150
