### ISSUE TITLE
Markdown does not correctly parse

### ISSUE THREAD

**Issue by ozgurnsahin** [pymupdf/RAG#193]
I got multiple pdf files that I parse with to_markdown() function generally it provides very good parsing but I got a problem with the document below. Markdown does not correctly parse the data elements table that starts at page 13 I will provide the output and my code below.

[r169.pdf](https://github.com/user-attachments/files/17935554/r169.pdf)
![image](https://github.com/user-attachments/assets/df5b02b2-f4cc-47ca-9cd5-ce4673bb1023)

with fitz.open(stream=pdf_file, filetype="pdf") as pdf:
            markdown_pages = pymupdf4llm.to_markdown(pdf, page_chunks=True, show_progress=False)

**Comment by JorjMcKie** [comment]
Sorry - this type of table is both, too complex and lacks too much information to be correctly detectable by PyMuPDF's table detector.
Vertical column borders are missing and positions of cell content at the same time does not deliver enough information.
This is also a PyMuPDF problem and not generated by this package.

So I'm afraid I have to say: out of scope.

**Comment by ozgurnsahin** [comment]
Thank you for your return, I understand genrally to_markdown() works very well I encountered this output just for this table and document do you think if I create the issue for the PyMuPDF they can support a fix or new feature? if not I will close the issue.

**Comment by JorjMcKie** [comment]
> Thank you for your return, I understand genrally to_markdown() works very well I encountered this output just for this table and document do you think if I create the issue for the PyMuPDF they can support a fix or new feature? if not I will close the issue.

I am also a maintainer of PyMuPDF 😎. I created the table detector, so you are talking to the right person already.
Table detection in general is very complex, and there always are cases that cannot be detected - no matter what tool you use.
You example cannot be detected and will not become detectable in the foreseeable future.

**Comment by ozgurnsahin** [comment]
Ow Okey thank you for the info and its a great library that makes our project develoment very easy I understand I will close the issue with this comment. Have a nice day
