### ISSUE TITLE
pymupdf4llm.to_markdown only lists str as return type

### ISSUE THREAD

**Issue by sebimohr** [pymupdf/RAG#194]
https://github.com/pymupdf/RAG/blob/b257182d0ac1ce7fda837e395c5382edf423e400/pymupdf4llm/pymupdf4llm/helpers/pymupdf_rag.py#L259

The function should not only list `str` as return type, but also `list[dict]` for when `page_chunks = True`

```python
def to_markdown(
    doc,
    *,
    pages: list = None,
    hdr_info=None,
    write_images=False,
    embed_images=False,
    image_path="",
    image_format="png",
    image_size_limit=0.05,
    force_text=True,
    page_chunks=False,
    margins=(0, 50, 0, 50),
    dpi=150,
    page_width=612,
    page_height=None,
    table_strategy="lines_strict",
    graphics_limit=None,
    fontsize_limit=3,
    ignore_code=False,
    extract_words=False,
    show_progress=True,
) -> str | list[dict]:
```

**Comment by JorjMcKie** [comment]
Thanks for your report!
This package is subject to many change activities. So we will take out type annotations for the time being as we do not want to deal with this type of issues now. Your observation spotted a place that has been forgotten in this process.
