### ISSUE TITLE
Consider following modern package design practice

### ISSUE THREAD

**Issue by HDembinski** [pymupdf/RAG#203]
Installing the package from source raises the warning that setup.py will soon become obsolete.

All Python packages should migrate to pyproject.toml.

Furthermore, it is good style to place the pymupdf4llm directory in a subdirectory called src, see https://packaging.python.org/en/latest/discussions/src-layout-vs-flat-layout/

**Comment by JorjMcKie** [comment]
Thanks for the hint. We will convert on occasion.
