### ISSUE TITLE
Markdown extraction bugs

### ISSUE THREAD

**Issue by ozgurnsahin** [pymupdf/RAG#205]
Hello I encountered corrupted markdowns I will provide the pdfs and original vs extracted outputs as examples below.
I am using simple code like below 

markdown_pages = pymupdf4llm.to_markdown("docs/domain1/2024_1689.pdf",page_chunks=True )

Markdown extract:
![image](https://github.com/user-attachments/assets/b541181f-14fa-4d9b-9c65-1319f004bc30)

Original text:
![image](https://github.com/user-attachments/assets/54f70ff2-949b-43a5-bab8-60099f05fc2c)

Markdown extract 2:
![image](https://github.com/user-attachments/assets/d94d2d64-476f-4f64-8a9a-b1e0c82c3a47)

Original text:
![image](https://github.com/user-attachments/assets/c2d50e24-a342-495d-905b-c451321772aa)

File: 
[2024_1689.pdf](https://github.com/user-attachments/files/17997107/2024_1689.pdf)

the corrupted texts is at the end of the page 2 and 3

this only occurs on this pdf as far as I used any these is more

**Comment by JorjMcKie** [comment]
This is not a bug, but a problem of setting the margin: by default stripes at top and bottom of pages are ignored (height 50 Points).
Set `margins=0` to enforce extracting the full page.

**Comment by ozgurnsahin** [comment]
Thank you for the reply man you are great!

**Comment by JorjMcKie** [comment]
I think those default margin settings are unfortunate. You are not the first one who got trapped that way.
Probably we should change that to `margins=0`.
