### ISSUE TITLE
Tests are not runnable

### ISSUE THREAD

**Issue by HDembinski** [pymupdf/RAG#206]
It looks like the tests in tests/pymupdf4llm/... 
haven't been run in a while. They require an "input.pdf" which is not part of the repository and not automatically downloaded from a suitable source.

Outsiders cannot run the tests.

But even apart from that, it looks like the API has changed and the tests still use an old API that does not exist anymore. This line fails:
`from pymupdf4llm.pymupdf4llm.llama_index.pdf_markdown_reader import PDFMarkdownReader`

**Comment by JorjMcKie** [comment]
This code part is not under our direct responsibility. Accessing / invoking LLama stuff has been provided by one of their collaborators.
While we do make sure that any API changes are also applied to here, we do not invest effort to update these test.

**Comment by HDembinski** [comment]
1) Why keep keep tests in your repo that don't work? As a fellow maintainer, I think one has to maintain tests that are under ones code control. You don't seem to have any other tests. Unit tests are essential to notice regressions.

2) What kind of test should I run then to see that the code works which I am developing?

3) "While we do make sure that any API changes are also applied to here, we do not invest effort to update these test." As far as I can see, the line that fails to work is failing because of a change in the package structure of pymupdf4llm, the `import pymupdf4llm.pymupdf4llm` does not work already.
