### ISSUE TITLE
issue with Heading since version 0.0.5

### ISSUE THREAD

**Issue by papipsycho** [pymupdf/RAG#30]
Hello, 

we remark some issue the heading of the pdf was correct on the version 0.0.3 since the version 0.0.5 didn't have any heading anymore.

**Comment by papipsycho** [comment]
I've test, but unfortunatly, is the same issue.

i will try to create test pdf for you

**Comment by JorjMcKie** [comment]
Could not reproduce the problem. Here is an example demonstrating successful use.
PDF look like this:

![image](https://github.com/pymupdf/RAG/assets/8290722/c734f708-3ba8-4ef1-8434-53425c876773)

Default extraction output (i.e. `margins=(0, 50, 0, 50)`) omits the page header:
```bash
data = pymupdf4llm.to_markdown("v110-changes.pdf")
print(data[:500])

# Pixmap

The alpha channel is now optional. Its presence is controlled by a new boolean parameter (called `alpha` ). This
has the following consequences:
```
Setting margins to 0 delivers the full page:
```bash
data = pymupdf4llm.to_markdown("v110-changes.pdf",margins=0)
print(data[:500])

**MuPDF v1.10 Changes and their Implications for PyMuPDF**

# Pixmap

The alpha channel is now optional. Its presence is controlled by a new boolean parameter (called `alpha` ). This
has the following consequences:
```

**Comment by JorjMcKie** [comment]
closed for lack of response over an extended period of time

**Comment by Elehiggle** [comment]
I was wondering why my code wasn't functioning as expected anymore. I had test pdfs that contains text and images. All of a sudden it would not get text anymore. margins=0 fixed it. I understand that this is a very early package, but maybe semver or better documentation on breaking changes could be a good idea 👍
