### ISSUE TITLE
Integration into langchain

### ISSUE THREAD

**Issue by zymbuzz** [pymupdf/RAG#32]
Hi, thank you for this great initiative. I was wondering if you are planning or already have an integration into a langchain? I am aware that the parent package pypmupdf is already integrated but I am keen on the capabilities of PyMuPDF4LLM.

Thank you very much.

**Comment by JorjMcKie** [comment]
We generally wait for input from an interested party and do not actively go hunting here.

But if it makes sense and still allows installation without adding mandatory dependencies, we are open to accept a PR.
