### ISSUE TITLE
Unable to parse 2-column documents

### ISSUE THREAD

**Issue by rahul-dhir-0047** [pymupdf/RAG#41]
Here is the document preview that I want to pass. 
![Screenshot 2024-06-13 105053](https://github.com/pymupdf/RAG/assets/162566515/b527c40a-b1be-4912-9044-73255b9cf03c)

Here is the parsed markdown format that i am getting (same for Llama Docs)
![Screenshot 2024-06-13 105633](https://github.com/pymupdf/RAG/assets/162566515/63703154-c488-49db-91e5-d6e3f9a9d9a8)

Facing the same issue.

**Comment by JorjMcKie** [comment]
Please always provide a reproducing document. An image is good for explaining things ... no more.

**Comment by JorjMcKie** [comment]
Duplicate of #40.

**Comment by rahul-dhir-0047** [comment]
> Please always provide a reproducing document. An image is good for explaining things ... no more.

Sorry I didnt attach it here. Please refer to the document below:
[Mediclassic-Individual-Insurance-Policy-v2.pdf](https://github.com/user-attachments/files/15913721/Mediclassic-Individual-Insurance-Policy-v2.pdf)

**Comment by JorjMcKie** [comment]
Partly solved in version 0.0.6.

The solution solves some problems but it is like with table recognition:
There will always be cases that escape a complete detection.
