### ISSUE TITLE
Chunking of text files

### ISSUE THREAD

**Issue by zymbuzz** [pymupdf/RAG#52]
Hello, and thanks a lot for this encouraging project.

I want to bring to your attention the issue arising when importing text files.
[myselectdoc.txt](https://github.com/user-attachments/files/15885770/myselectdoc.txt)

When applying the to_markdown function, the text is chunked into pieces with the separator "-----". Is it possible to disable chunking?

When I specify input margins=[0, 0, 0, 0], some text is not lost, but chunking still does not happen. 

The issue may be irrelevant to your project goal, but it might be interesting because you allow for non-pdf files.

**Comment by JorjMcKie** [comment]
Solved in version 0.0.6.
