### ISSUE TITLE
When the image is at the very end of the page, the image cannot be displayed

### ISSUE THREAD

**Issue by rexyan** [pymupdf/RAG#53]
Hello and thanks for this wonderful project.

However, I found a problem when using the image at the very end of the page, using write_images=True can not export the image

In addition, I want to improve the resolution of the picture, how to achieve it?

**Comment by JorjMcKie** [comment]
There is a default margin setting which leads to ignoring the top and bottom rectangles of height 50.
If you set `margins=0` you see everything again.

**Comment by JorjMcKie** [comment]
Ah I forgot to mention, that we will include a DPI parameter for setting the resolution of exported images.
