### ISSUE TITLE
The Markdown syntax for images is always included in the Markdown output.

### ISSUE THREAD

**Issue by tamdao** [pymupdf/RAG#67]
I use v0.0.8 with `to_markdown(doc)` by default write_images=False But the markdown syntax for images is always included in the Markdown output.

[saint.pdf](https://github.com/user-attachments/files/16114860/saint.pdf)
[output.md](https://github.com/user-attachments/files/16114865/output.md)

There is another issue with this file. When I set write_images=True, it doesn't work correctly. Even though the file doesn't contain any images, the result includes some white images.

**Comment by JorjMcKie** [comment]
Cannot reproduce!
The is the output I am getting
![image](https://github.com/pymupdf/RAG/assets/8290722/16d2d976-2768-4bed-aaab-3271ba994e86)
[saint.md](https://github.com/user-attachments/files/16115823/saint.md)

**Comment by JorjMcKie** [comment]
Your PDF contains multiple areas with a white background - written as vector graphics.
Version 0.0.8 has an improved logic that ignores vector graphics which only consist of background coloring.
**_Significant_** vector graphics are converted to images and treated like images.
A significant vector graphic must also contain stroked drawings (which are not part of the drawing rectangle's border).

**Comment by tamdao** [comment]
@JorjMcKie Thanks for your response. I apologize for the confusion; I checked the wrong version.
