### ISSUE TITLE
Unexpected results in pymupdf4llm but pymupdf works

### ISSUE THREAD

**Issue by saturosfz** [pymupdf/RAG#71]
[36.pdf](https://github.com/user-attachments/files/16177635/36.pdf)
Just repeating \xef\xbf\xbd

**Comment by JorjMcKie** [comment]
This comes from using different default extraction flags. In pymupdf4llm we do not use flag bit `pymupdf.TEXT_CID_FOR_UNKNOWN_UNICODE` which causes to use the **_glyph number_** as Unicode value, if the Unicode number is not present in the font.

In version 0.0.9 I will revert this. I checked that your file can be processed with this flag bit set.

**Comment by JorjMcKie** [comment]
Fixed in v0.0.9.
