### ISSUE TITLE
minimum area for images & vector graphics

### ISSUE THREAD

**Issue by hewliyang** [pymupdf/RAG#74]
![image](https://github.com/user-attachments/assets/95795d03-2aa2-44f0-8fe8-3355e0cfdda8)

For poorly formatted elements like this table, `page.get_image_info()` will return a large number of erroneous "images" like below. Probably the right decision is to set `graphics_limit` and ignore the page.

![ex1](https://github.com/user-attachments/assets/66a04ef8-efa8-4842-9ba8-25cb0ae052ff)

![ex2](https://github.com/user-attachments/assets/c1f8557b-96e0-491a-a74f-d49e2afb0d15)

While this is an indication the layout detection is likely to not work well anyways, I'm thinking if it would be beneficial to add the ability to pass in an extra parameter `min_area` such that we ignore images with `img['height'] * img['width'] < min_area` as a simple threshold or if there is any feasible solution to this issue.

This would also fix the issue of outputting small logo watermarks located at the corners of documents which may exist on every single page.

**Comment by JorjMcKie** [comment]
Thanks for your post.
Valid point! We probably need a check for generally insignificant images: small areas, unicolor etc.

**Comment by JorjMcKie** [comment]
Fixed with v0.0.10.
