### ISSUE TITLE
Make it only one pymupdf4llm module instead of two (pymupdf4llm, pdf4llm)

### ISSUE THREAD

**Issue by dantetemplar** [pymupdf/RAG#82]
I think that deprecating the `pdf4llm` module will improve the developer's experience: 

- It will be easier for the project to understand the source code of the library
- It will be easier to version the library (for now, version differentiate between packages, and there is no changelog for `pdf4llm` I guess) 
- It will also make it easy to integrate additional tools into library development (Poetry for example)
- It will allow to use only one README.md in repository root (now there are 3 different README.md files)

For example, I had many questions about why it was done this way, and how exactly imports work in the pdf4llm folder.

It is possible to release a patch to `pdf4llm` that will cause `DeprecationWarning` when importing a module.

I will attach PR.

**Comment by dantetemplar** [comment]
I noticed that you do a lot for pymupdf, it's really cool!

@JorjMcKie

**Comment by dantetemplar** [comment]
Deprecation of module:

https://github.com/dantetemplar/pymupdf4llm/commit/d708fbdc8920b82570867c2fdf9e1dd6455f9ad1

**Comment by dantetemplar** [comment]
For deprecating build and publish `pdf4llm`: https://github.com/dantetemplar/pymupdf4llm/commit/d708fbdc8920b82570867c2fdf9e1dd6455f9ad1
And just delete pdf4llm folder after that.

**Comment by dantetemplar** [comment]
Also I suggest to move out stuff not related to pymupdf4llm package: `examples` folder (move content to docs or artifex blog), replace README.md in the root with pymupdf4llm/README.md

**Comment by JorjMcKie** [comment]
Thank you for your appreciation and your contributions!
I am glad you like it.
There are good reasons why we have and will keep pdf4llm as an alias. These reasons are not technical, therefore your considerations - while valid from a technical perspective - do not apply here.

**Comment by jackbravo** [comment]
What are those reasons? 😅
