### ISSUE TITLE
Use Poetry to resolve dependencies, lock them, build and publish package

### ISSUE THREAD

**Issue by dantetemplar** [pymupdf/RAG#84]
Currently the `pymupdf4llm` package uses `setup.py` for managing dependencies, packaging, and distribution. To modernize the package management and streamline the development workflow, I propose to migrate to Poetry. Poetry will handle dependencies, lock them to ensure reproducible builds, and facilitate the build and publication process.

### Benefits of Using Poetry:

- **Dependency Management**: Automatically resolves and locks dependencies, ensuring consistency.
- **Simplified Publishing**: Streamlines the build and publish process with simple commands.
- **Modern Tooling**: Aligns with current best practices in Python packaging.

### Action Required:

- Migrate the existing `setup.py` configuration to a `pyproject.toml` managed by Poetry.
- Test the new setup to ensure all functionalities remain intact.

### How to build and publish then:

- Increase version by `poetry version <bump-rule>`:
```
 bumps the version of  the project and writes the new version back to pyproject.toml if a valid
  bump rule is provided.
  
  The new version should ideally be a valid semver string or a valid bump rule:
  patch, minor, major, prepatch, preminor, premajor, prerelease.
```
- Then build and publish by `poetry publish --build` (also need to [configure credentials](https://python-poetry.org/docs/repositories/#configuring-credentials))

**Comment by dantetemplar** [comment]
I will make PR for it

**Comment by dantetemplar** [comment]
Package on TestPypi using Poetry publish:
https://test.pypi.org/project/pymupdf4llm/

**Comment by JorjMcKie** [comment]
Thank you for your suggestion.
This repository is closely linked to PyMuPDF which has its own tools to achieve what we want. Over time, this package offspring will reuse what we have there.
