### ISSUE TITLE
Bug in `is_significant` function 

### ISSUE THREAD

**Issue by dantetemplar** [pymupdf/RAG#88]
In `pymupdf_rag.py:196` "q" stands for Quad type but it should be "qu" I guess. That leads to runtime error.

 https://github.com/pymupdf/RAG/blob/8c0f5009f3d121a9679445b7b551318d77dd967c/pymupdf4llm/pymupdf4llm/helpers/pymupdf_rag.py#L196

**Comment by Stephen-S-H** [comment]
I can confirm this error, and that changing this line to 
`elif itm[0] =="qu":`
does fix the issue. I've changed to to this just to be safe for the time being:
`            elif itm[0] in ("q", "qu"):  # quad`

**Comment by bhashithe-air** [comment]
Thanks both, yes changing to 'qu' worked! Can send a PR if needed.

**Comment by bhashithe-air** [comment]
@dantetemplar #93 seems to do the same fix, so i closed mine.

**Comment by JorjMcKie** [comment]
Fixed in v0.0.11.
